name: build-next

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 12.6.0
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - uses: redhat-actions/buildah-build@v2
        with:
          image: extension-wslc
          tags: next ${{ github.sha }}
          containerfiles: build/Containerfile
          context: .
          oci: true
